version: 2

defaults: &defaults
  docker:
    - image: circleci/node:latest
  working_directory: ~/repo

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - run: npm test
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  deploy_staging:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: deploy to staging
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/thankoverflow-staging.git master
      - run:
          name: smoke test for staging
          command: curl --fail https://thankoverflow-staging.herokuapp.com/

  deploy_prod:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: deploy to prod
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/thankoverflow.git master
      - run:
          name: smoke test for prod
          command: curl --fail https://thankoverflow.herokuapp.com/

workflows:
  version: 2
  ci_pipeline:
    jobs:
      - test
      - deploy_staging:
          requires:
            - test
      - hold:
          type: approval
          requires:
            - deploy_staging
      - deploy_prod:
          requires:
            - hold
