version: 2

references:
  container_config: &container_config
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo

jobs:
  checkout_and_install_dependencies:
    <<: *container_config
    executor: node_exec
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  deploy_staging:
    working_directory: ~/repo
    steps:
      - run:
          name: deploy to staging
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/thankoverflow-staging.git master

  deploy_prod:
    working_directory: ~/repo
    steps:
      - run:
          name: deploy to prod
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/thankoverflow.git master

workflows:
  version: 2
  ci_pipeline:
    jobs:
      - checkout_and_install_dependencies
      - deploy_staging:
          requires:
            - checkout_and_install_dependencies
      - deploy_prod:
          type: approval
          requires:
            - deploy_staging
